# -*- coding: utf-8 -*-
"""streamlit_app.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wCfitPn6Az0rtP38HpCeCLpxPQVuBRyR
"""

import pickle
import streamlit as st

# yukarıdakileri fonkisyona alalım
def recommend_movie(movie):
  index = netflix_data_v2[netflix_data_v2['TITLE']==movie].index[0]
  # benzerlik değerlerine göre sıralayıp uzaklık değerine atıyoruz
  distance = sorted(list(enumerate(similarity[index])), reverse=True, key=lambda x:x[1])
  recommended_movies_name = []
  # Use the recommendations to get movie indices
  recommended_movie_indices = [i[0] for i in distance[:10]]
  # Extract and display the recommended movie titles
  recommended_movie_titles = netflix_data_v2.iloc[recommended_movie_indices]['TITLE']
  st.write("Recommended Movies:")
  st.write(recommended_movie_titles)

  return recommended_movies_name


html_temp = """
<div style="background:#025246 ;padding:10px">
<h2 style="color:white;text-align:center;"> Netflix Movie Recommendation </h2>
</div>
    """
st.markdown(html_temp, unsafe_allow_html = True)
st.markdown("<br>", unsafe_allow_html=True)
netflix_data_v2 = pickle.load(open('artifacts/netflix_titles.pkl','rb'))
similarity = pickle.load(open('artifacts/recommend_movie.pkl','rb'))


movie_list = netflix_data_v2['TITLE'].values
select_movie = st.selectbox(
    "Please type or select a movie for recommendation",
    movie_list
)
st.markdown("<br>", unsafe_allow_html=True)
if st.button('Show Recommendation'):
    recommended_movie_names = recommend_movie(select_movie)
   
